# Setup

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: USE_LOCK=false
    - php: 7
      env: USE_LOCK=false
    - php: 7.1
    - php: 7.2

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php_cs.cache

# Build Lifecycle
before_install:
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer validate

install:
  - |-
    if [[ "$USE_LOCK" == "false" ]];
    then
      composer update;
    else
      composer install;
    fi;

before_script:
  - 'curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@composer.lock'

script:
  - composer cs
  - composer test

# Build Notifications
notifications:
  email:
    on_success: change
    on_failure: change
