language: php

matrix:
  include:
    - php: 5.6
      env: WITH_LOWEST=true
    - php: 7.0
    - php: 7.1

before_install:
  - composer validate

install:
  - if [[ "$WITH_LOWEST" == "true" ]]; then composer update --prefer-lowest; else composer install --prefer-source; fi

script:
  - composer cs
  - composer test

notifications:
  email: false
